spring.application.name=bankproj
spring.datasource.url=jdbc:postgresql://localhost:5432/bankproj
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}